### ISSUE TITLE
Error when trying to rip track

### ISSUE THREAD

**Issue by shillshocked** [robbeofficial/spotifyripper#19]
Logging in, please wait...
Logged in!
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "./jbripper.py", line 101, in run
    link = Link.from_string(sys.argv[3])
SpotifyError: Failed to get link from a Spotify URI

**Comment by shillshocked** [comment]
Never mind, looks like I had the syntax wrong. Note that the default spotify urls don't work, you have to enter them like this:
python2 ./jbripper.py login pass spotify:track:3utrVV69mUvCAIU81Pxj48

**Comment by droopified** [comment]
Unrelated but are you getting no id3 info errors?
