### ISSUE TITLE
Authentication with unknown password

### ISSUE THREAD

**Issue by d3v-null** [robbeofficial/spotifyripper#38]
Hey,
Just wondering if you have any suggestions on how to get this to work if your Spotify account is authenticated with Facebook. I can't create a Spotify account with the email I'm already using for this account, and I can't reset my password because it says i'm authenticated with Facebook.

Any suggestions?

**Comment by wuestkamp** [comment]
Check the settings in your Spotify Account, you can convert a facebook account to a normal account. That's what I did.

**Comment by shakisha** [comment]
@derwentx  i think you can close this issue-

**Comment by d3v-null** [comment]
For reference, it's best to contact support and they will sort it out.
Thanks
