### ISSUE TITLE
bitrate set to 96k

### ISSUE THREAD

**Issue by pheex** [robbeofficial/spotifyripper#6]
The birate selected to retrieve spotify stream is set to 96kbps, not according to the comment:
self.session.set_preferred_bitrate(2) # 320 bps

2 is 96
0 is 160
1 is 320 kbps

source : https://developer.spotify.com/docs/libspotify/11.1.60/group__session.html

**Comment by djsuszi** [comment]
@pheex can you contact about HapCan and OpenHab ?
http://hapcan.com/forum/viewtopic.php?f=3&t=803&p=2147 ?
